# Generated by Django 4.2.5 on 2023-09-26 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('Agendado', 'Agendado'), ('Cancelado', 'Cancelado'), ('Concluído', 'Concluído')], max_length=20)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromissos_criados', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='compromissos_participantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
