# Generated by Django 4.2.5 on 2023-09-28 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compromisso',
            options={'ordering': ('data',), 'verbose_name_plural': 'Compromissos'},
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='participantes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
